### ISSUE TITLE
Minimum GPU settings for testing

### ISSUE THREAD

**Issue by morsingher** [whubaichuan/M3VSNet#10]
Hi, thanks for the great work. I was trying to run eval.sh on DTU, but I keep receiving the following error:

`RuntimeError: CUDA out of memory. Tried to allocate 2.71 GiB (GPU 0; 11.17 GiB total capacity; 6.39 GiB already allocated; 2.46 GiB free; 8.29 GiB reserved in total by PyTorch)`

My GPU is a Tesla K80. I'm aware that training won't probably work on that, but I'm a bit surprised that 12 GB of memory are not enough even for testing. So, my questions are:

1) What is the minimum GPU configuration you would expect to work?
2) Do you recommend some tricks to make it work?

**Comment by whubaichuan** [comment]
@morsingher could you tell me the size of the image you test?

**Comment by morsingher** [comment]
I just followed the steps in your readme for evaluating with DTU, so it's the image size of the DTU dataset. Anyway, I managed to make it work by reducing `numdepth` and increasing `interval_scale` accordingly.

**Comment by whubaichuan** [comment]
@morsingher Maybe you should reduce the size of inputting images. Try 1/4 size of the original size.

**Comment by morsingher** [comment]
Ok, I will try. I was a bit surprised since I can run state-of-the-art methods like https://github.com/FangjinhuaWang/PatchmatchNet without issues. Maybe it's just because using MVSNet as a backbone is demanding a lot of memory. Anyway, thanks for your time.
