### ISSUE TITLE
Generalization Ablation on Tanks & Temples

### ISSUE THREAD

**Issue by cyr999** [whubaichuan/M3VSNet#11]
Hello, we are very interested in your work. We have tested the qualitative result on Tanks &Temples dataset
![Horse](https://user-images.githubusercontent.com/68780990/137236075-5cbd03b4-4f39-4e9c-9416-35171ceaa8f9.png)
![Family](https://user-images.githubusercontent.com/68780990/137236004-0352b6fd-91ea-421d-9e98-a48aaa26661e.png)
, and the result is not as good as the paper result. Could you please share your test code for Tanks &Temples?

Looking forward to your reply!
Thanks.

**Comment by whubaichuan** [comment]
@cyr999 actually, you need to change the hyperparameters for T&T test such as the depth interval to get better results.
