### ISSUE TITLE
Number of GPUs

### ISSUE THREAD

**Issue by czha5168** [whubaichuan/M3VSNet#2]
Hi Baichuan, 
It's really an interesting paper. Looking forward to the release of your source code.
May I ask the number of GPUs that you used during your method development? Thanks!

**Comment by whubaichuan** [comment]
@czha5168 when I trained the model, I use 4 GPUs for the batchsize 4. In fact, the only one GPU also works.

**Comment by czha5168** [comment]
@whubaichuan Thanks for your thunder reply!

**Comment by whubaichuan** [comment]
@czha5168 The code is available now.
