### ISSUE TITLE
Can you share me the depth map of DTU test sets

### ISSUE THREAD

**Issue by zhuixunforever** [whubaichuan/M3VSNet#4]
How do you get a high-resolution depth map? Mvsnet seems to provide only 128 * 160 depth maps. Can you share the high-resolution depth map with me? Thank you very much.

**Comment by whubaichuan** [comment]
@zhuixunforever I don't need the high-resolution depth map.

**Comment by zhuixunforever** [comment]
@whubaichuan in your paper, "During the testing phase, the resolution of input image is 1600 × 1200". in other words, you use 400*296 depth map to evaluate, and get table3 and table 4 in your paper, but mvsnet  seems to provide only 128 * 160 depth maps. I don't know if I got it right.

**Comment by whubaichuan** [comment]
@zhuixunforever I crop the image to a small size as mvsnet_pytorch doing.

**Comment by whubaichuan** [comment]
@zhuixunforever The code is available now.
