### ISSUE TITLE
Is this speed of convergence normal?

### ISSUE THREAD

**Issue by tau-yihouxiang** [whubaichuan/M3VSNet#7]
I just trained the model for one epoch on two GPUs, and the tensorboard summary is shown in following figure. I think the convergence speed is pretty low.

<img width="1135" alt="截屏2021-03-31 20 37 25" src="https://user-images.githubusercontent.com/23013154/113145358-e87db400-9260-11eb-83f1-fe8ec97b005a.png">

**Comment by Sun-Xinnnnn** [comment]
Can you tell me the version of pytorch you are using？ @tau-yihouxiang

**Comment by tau-yihouxiang** [comment]
Pytorch 1.7

**Comment by whubaichuan** [comment]
@tau-yihouxiang Yes, the time of the training process is long. How long have you taked at present?
