### ISSUE TITLE
Question about mask_final?

### ISSUE THREAD

**Issue by tau-yihouxiang** [whubaichuan/M3VSNet#8]
I noticed that the code introduces mask_final to calculate depth accuracy:
_AbsDepthError_metrics(depth_est, depth_gt, mask_final > 0.5)_

I am confused, since other methods calculate the accuracy in the whole mask_gt.

**Comment by whubaichuan** [comment]
@tau-yihouxiang areas out of mask are useless. Thus, I don't calculate the whole mask.
