### ISSUE TITLE
loss.backward() error

### ISSUE THREAD

**Issue by Sun-Xinnnnn** [whubaichuan/M3VSNet#9]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 3, 3]] is at version 17; expected version 13 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

i create same env as author,such as pytorch=1.0.1,opencv and numpy.
I want to know what went wrong, and I feel that the program should be improved.

**Comment by whubaichuan** [comment]
@zhang-snowy please use a=a+b not a+=b

**Comment by liushifu12138** [comment]
please help me
i have use a=a+b，but went wrong

**Comment by whubaichuan** [comment]
> please help me i have use a=a+b，but went wrong

@liushifu12138 Please see here [the same problem](https://github.com/whubaichuan/M3VSNet/issues/5#issuecomment-766288557). The reason is still the version of pytorch I think
